### ISSUE TITLE
Attach APK of free version to releases?

### ISSUE THREAD

**Issue by IzzySoft** [domoticz/domoticz-android#382]
With the project being open-source, are there any intentions to make the free version available freely – i.e. outside from Google Play? I think e.g. of F-Droid, or at least attaching the `.apk` to `releases/` here at Github (where I could pick it and add it to [my repo](https://android.izzysoft.de/repo) for others to fetch using the F-Droid client ;).

**Comment by pierre-guillot** [comment]
It seems the domoticz-lite can work on android devices whitout google-play services : 
- On a fire 7' (2015) : it work
- On a cyanogen mod 13 : it work

Maybe google-play is only requiered for domoticz premium? Why not provide two versions : 
- Domoticz-lite without googe-play services : In this case, you can attach apk on github and you can put it on fdroid repo
- Domoticz premium with googe-play services : on play store

**Comment by IzzySoft** [comment]
Even if it would require some of the GServices, the [microG framework](https://github.com/microg) would cover most of it (as long as it's not `vending.CHECK_LICENSE` that is), see [implementation status](https://github.com/microg/android_packages_apps_GmsCore/wiki/Implementation-Status) for details.

**Comment by tbart** [comment]
Any info on why the status of this issue is wontfix when there seem to be easy ways to achieve a solution?
The user base could be vastly increased if this app pops up in f-droid. There are many open source savvy users that only have f-droid as their app store and I know a lot of them are active testers or even devs. There's nothing to lose, the project is open source already, so make the best out of it!
