### ISSUE TITLE
Unable to connect - reverse proxy configuration

### ISSUE THREAD

**Issue by Potjoe-97** [domoticz/domoticz-android#562]
Hi everyone, 

I've noticed today after having set up an nginx reverse proxy on the rasperry pi running my domoticz instance, that I cannot configure the app anymore. In my configuration, domoticz can be accessed directly through `https://<myreverseproxy.com>/domoticz`., with a basic auth authentification. Then, I do not have to fill the "port" section in paramaters. And the issue seems to be coming from here. Indeed, the app tries to connect through `https://<myreverseproxy.com>/:/domoticz` when i leave the port parameter empty, or to `https://<myreverseproxy.com>/:443/domoticz` when 443 value is entered, resulting to an incorrect configuration. Am I missing something or is it an issue with the way the app read the port parameter ?

Thanks everyone, 
Potjoe

**Comment by Catfriend1** [comment]
Since the latest gplay release I am very disappointed. What originally started out as a very good paid app now is a desaster since 2018/09 for me.

First, around 2018/09, the apps permission detection was broken. After updating back then it always threw an error "user has no permission on switch" which was not true and I could not switch anymore anything. Around 2019/10 and endless update attempts, it was fixed and I could use the app again.

Secondly, I've got my domoticz running on https://dns.tld:420 with a sophos web application firewall (= reverse proxy) in front of it limiting which users are passed through via basic auth (e.g. user1 , user2 allowed, admin1 disallowed).

When I updated the app to the latest gplay version yesterday it totally stopped working as it can no longer login via basic auth.

I'm fed up, sorry. Taking my dollars ~ 2016 and making things worse tying my hands to the play store is no good user experience. I'm no going back to release 0.2.25 from 2018 which works without any problem. 

Please, please get things right again. If you need my help, logs, etc. feel free to contact me. Btw is there any APK of the paid version available I could meanwhilst install to my phone and is dated around 2020/01 ? Paid apps are unfortunately not rollback'able via apk mirror and I can't download a full APK with AuroraStore as it downloads app bundle fragments which cannot be installed one by one to my unrooted phone.

Anyways, I'd also like to thank you that I got this cool app I've used over years. I'm angry but not ungrateful.

**Comment by galadril** [comment]
Dear catfriend,

Its not my fault this time. I've been asked to remove basic auth support by gizmocus.. Basic auth is going to be removed from Domoticz as well soon...

**Comment by galadril** [comment]
@Catfriend1 im  building a new hybrid version with basic auth and cookie based login implemented

**Comment by Catfriend1** [comment]
Oh, OK. Sorry I didn't know that. Well a hybrid version makes sense so we could have more time to plan and do the update. (I've got some very old and lsrge script set interfacing my domoticz, depending on an old openzwave version.)

**Comment by galadril** [comment]
New version coming without 2 hours eta

**Comment by Catfriend1** [comment]
Updated to premium v512 and still cannot login via basicAuth. Just fyi.

Went back to the last-working 488, settings import failed. Went back to 0.2.25 (2018/11) , import success,  updated to v488 premium and it works fine.

**Comment by galadril** [comment]
v0.2.221 didn't worked with basic auth?? because i've tested this with basic auth on my server..

**Comment by Catfriend1** [comment]
Correct, 0.2.221 (7463).512 did not work for me. Should I collect logs, what would you need to diagnose the problem? Or can I trace on the reverse proxy which URLs get called with which result and provide you with that info?

**Comment by galadril** [comment]
you could create an account for me and send the server details to domoticz@hnogames.nl

**Comment by Catfriend1** [comment]
Ok, I've tried logging in with the most recent premium build #513 as a fresh installation on a new device. It says "Domoticz version 4.10717, 43 devices found" and then "something went wrong, invalid login data" (translated from german). Will setup a test account for you, may take some time.

**Comment by Catfriend1** [comment]
Thank you for 0.2.222 (7486) 513 so much :-) 👍 !!!
It didn't work because my Sophos UTM WAF reverse proxy blocked the unhardened form data requested by the app via url "/json.htm?type=command&param=logincheck&username=*". I've put this string to the exception whitelist and now it works well with basicAuth using Domoticz 4.10717. You're good maintainer :-). Donation link welcome ;)

**Comment by galadril** [comment]
Your welcome.
It's not needed at all, but there is a link for donations on bottom of the
github readme.

Op do 14 mei 2020 om 10:40 schreef Catfriend1 <notifications@github.com>:
