### ISSUE TITLE
No more premium version ?

### ISSUE THREAD

**Issue by rezzalex** [domoticz/domoticz-android#652]
Thank you for the latest  version.
It seems only 1 version will be maintained in the future.
What about the premium version and it's features ?

Thanks

**Comment by galadril** [comment]
Hi

Yes you are right.
I already wrote about this on the domotica forum.

I'm trying to keep these apps up to date, but there are not many new premium buyers.
So as I do want to continue my support on the apps it's now (6years later) more normal to build this premium features as a yearly subscription. So that's what I'm changing along with a really big update.

Premium is also getting there big update but then the support is going to stop. You can ofcourse still continue to use that app it you like?

**Comment by galadril** [comment]
Yes all current premium features are going to be a yearly subscription fee.

**Comment by rezzalex** [comment]
Hello,

I am migrating to the new "unique" version, that will be updated, How can I be sure not to lose my current premium features?

**Comment by kitopopo** [comment]
Dear friend @galadril 

I have the old domoticz home automation payment application. I have premium features like widgets. This application will no longer receive more updates. I need to know which is the current application that will receive updates, is that application an annual subscription? I await your news, thanks in advance. best regards

**Comment by galadril** [comment]
Currently both are still on the same lvl of updates
